services:
  fastapi_endpoint:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      LLM_URL: "http://host.docker.internal:11434"
    depends_on:
      - ollama

  ollama:
    image: "ollama/ollama:latest"
    env_file:
      - .env
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
    runtime: nvidia

volumes:
  ollama_models: